CREATE SEQUENCE depa_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  
  
CREATE SEQUENCE locali_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  
  
CREATE SEQUENCE itr_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  