CREATE SEQUENCE depa_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  
  
CREATE SEQUENCE locali_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  
  
CREATE SEQUENCE itr_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  
  
CREATE SEQUENCE analistas_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  
  
CREATE SEQUENCE areas_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  
  
CREATE SEQUENCE constancias_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  
  
CREATE SEQUENCE estud_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  
  
CREATE SEQUENCE event_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  
  
CREATE SEQUENCE justi_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  
  
CREATE SEQUENCE recl_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;    


CREATE SEQUENCE stat_cert_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  
  
CREATE SEQUENCE tutores_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCACHE;  

COMMIT;  