--------------------------------------------------------
--  File created - Saturday-July-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ANALISTAS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."ANALISTAS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 36 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence AREAS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."AREAS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CONSTANCIAS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."CONSTANCIAS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DEPA_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."DEPA_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 62 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ESTUD_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."ESTUD_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 38 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence EVENT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."EVENT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ITR_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."ITR_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 19 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence JUSTI_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."JUSTI_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOCALI_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."LOCALI_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 140 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RECL_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."RECL_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ESTADOS
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."SEQ_ESTADOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_EVENTO
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."SEQ_ID_EVENTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MODALIDADES
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."SEQ_MODALIDADES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence STAT_CERT_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."STAT_CERT_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TUTORES_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##PROYECTO"."TUTORES_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 19 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ANALISTAS
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."ANALISTAS" 
   (	"ID_ANALISTA" NUMBER(*,0), 
	"NOMBRE_USUARIO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ANALISTA_EVENTO
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."ANALISTA_EVENTO" 
   (	"ID_ANALISTA" NUMBER(*,0), 
	"ID_EVENTO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AREAS
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."AREAS" 
   (	"ID_AREA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONSTANCIAS
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."CONSTANCIAS" 
   (	"ID_CONSTANCIA" NUMBER(*,0), 
	"ID_ESTUDIANTE" NUMBER(*,0), 
	"ID_EVENTO" NUMBER(*,0), 
	"ID_ANALISTA" NUMBER(*,0), 
	"DETALLE" VARCHAR2(250 BYTE), 
	"FECHA_HORA" DATE, 
	"TIPO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTOS
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."DEPARTAMENTOS" 
   (	"ID_DEPARTAMENTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ID_ITR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTADOS
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."ESTADOS" 
   (	"ID_ESTADO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ACTIVO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANTES
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."ESTUDIANTES" 
   (	"ID_ESTUDIANTE" NUMBER(*,0), 
	"NOMBRE_USUARIO" VARCHAR2(100 BYTE), 
	"GENERACION" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANTE_EVENTO
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."ESTUDIANTE_EVENTO" 
   (	"ID_ESTUDIANTE" NUMBER(*,0), 
	"ID_EVENTO" NUMBER(*,0), 
	"CALIFICACION" NUMBER(3,2), 
	"ASISTENCIA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENTOS
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."EVENTOS" 
   (	"ID_EVENTO" NUMBER(*,0), 
	"FECHA_HORA_INICIO" DATE, 
	"FECHA_HORA_FINAL" DATE, 
	"TITULO" VARCHAR2(100 BYTE), 
	"LOCALIZACION" VARCHAR2(100 BYTE), 
	"TIPO_EVENTO" VARCHAR2(50 BYTE), 
	"MODALIDAD" VARCHAR2(50 BYTE), 
	"ID_ITR" NUMBER(*,0), 
	"ID_ESTADO" NUMBER(*,0), 
	"ID_MODALIDAD" NUMBER(*,0), 
	"ID_TIPO" NUMBER(*,0), 
	"ACTIVO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITR
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."ITR" 
   (	"ID_ITR" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ACTIVO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JUSTIFICACIONES
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."JUSTIFICACIONES" 
   (	"ID_JUSTIFICACION" NUMBER(*,0), 
	"ID_ESTUDIANTE" NUMBER(*,0), 
	"ID_EVENTO" NUMBER(*,0), 
	"ID_ANALISTA" NUMBER(*,0), 
	"DETALLE" VARCHAR2(250 BYTE), 
	"FECHA_HORA" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCALIDADES
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."LOCALIDADES" 
   (	"ID_LOCALIDAD" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ID_DEPARTAMENTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MODALIDADES
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."MODALIDADES" 
   (	"ID_MODALIDAD" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ACTIVO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECLAMOS
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."RECLAMOS" 
   (	"ID_RECLAMO" NUMBER(*,0), 
	"ID_ESTUDIANTE" NUMBER(*,0), 
	"ID_EVENTO" NUMBER(*,0), 
	"ID_ANALISTA" NUMBER(*,0), 
	"DETALLE" VARCHAR2(250 BYTE), 
	"FECHA_HORA" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATUS_CERTIFICADOS
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."STATUS_CERTIFICADOS" 
   (	"ID_STATUS" NUMBER(*,0), 
	"NOMBRE_ACCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATUS_CONSTANCIA
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."STATUS_CONSTANCIA" 
   (	"ID_STATUS" NUMBER(*,0), 
	"ID_CONSTANCIA" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATUS_JUSTIFICACION
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."STATUS_JUSTIFICACION" 
   (	"ID_STATUS" NUMBER(*,0), 
	"ID_JUSTIFICACION" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATUS_RECLAMO
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."STATUS_RECLAMO" 
   (	"ID_STATUS" NUMBER(*,0), 
	"ID_RECLAMO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPOSEVENTOS
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."TIPOSEVENTOS" 
   (	"ID_TIPO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TUTORES
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."TUTORES" 
   (	"ID_TUTOR" NUMBER(*,0), 
	"NOMBRE_USUARIO" VARCHAR2(100 BYTE), 
	"TIPO" VARCHAR2(75 BYTE), 
	"ID_AREA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TUTOR_EVENTO
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."TUTOR_EVENTO" 
   (	"ID_TUTOR" NUMBER(*,0), 
	"ID_EVENTO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "C##PROYECTO"."USUARIOS" 
   (	"NOMBRE_USUARIO" VARCHAR2(100 BYTE), 
	"NOMBRE1" VARCHAR2(50 BYTE), 
	"NOMBRE2" VARCHAR2(50 BYTE), 
	"APELLIDO1" VARCHAR2(100 BYTE), 
	"APELLIDO2" VARCHAR2(100 BYTE), 
	"FEC_NAC" DATE, 
	"GENERO" CHAR(1 BYTE), 
	"ID_DEPARTAMENTO" NUMBER(*,0), 
	"ID_LOCALIDAD" NUMBER(*,0), 
	"MAIL_INSTITUCIONAL" VARCHAR2(250 BYTE), 
	"CONTRASENIA" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(9 BYTE), 
	"DOCUMENTO" VARCHAR2(8 BYTE), 
	"ACTIVO" NUMBER(1,0), 
	"MAIL_PERSONAL" VARCHAR2(250 BYTE), 
	"ID_ITR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PROYECTO.ANALISTAS
SET DEFINE OFF;
Insert into C##PROYECTO.ANALISTAS (ID_ANALISTA,NOMBRE_USUARIO) values (33,'gluca');
Insert into C##PROYECTO.ANALISTAS (ID_ANALISTA,NOMBRE_USUARIO) values (26,'p.perez');
Insert into C##PROYECTO.ANALISTAS (ID_ANALISTA,NOMBRE_USUARIO) values (27,'rodrigo.romano');
Insert into C##PROYECTO.ANALISTAS (ID_ANALISTA,NOMBRE_USUARIO) values (35,'romi.caubarrere');
REM INSERTING into C##PROYECTO.ANALISTA_EVENTO
SET DEFINE OFF;
REM INSERTING into C##PROYECTO.AREAS
SET DEFINE OFF;
Insert into C##PROYECTO.AREAS (ID_AREA,NOMBRE,DESCRIPCION) values (1,'Programaci�n','Area encargada de las materias referentes al desarrollo de sistemas informaticos');
Insert into C##PROYECTO.AREAS (ID_AREA,NOMBRE,DESCRIPCION) values (2,'Testing','Area encargada de las materias referentes a la calidad de los productos de software');
Insert into C##PROYECTO.AREAS (ID_AREA,NOMBRE,DESCRIPCION) values (3,'Base de datos','Area encargada de las materias referentes a los sistemas de persistencia de datos');
Insert into C##PROYECTO.AREAS (ID_AREA,NOMBRE,DESCRIPCION) values (4,'Infraestructura','Area encargada de las materias referentes a los servicios de infraestructura TI');
REM INSERTING into C##PROYECTO.CONSTANCIAS
SET DEFINE OFF;
REM INSERTING into C##PROYECTO.DEPARTAMENTOS
SET DEFINE OFF;
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (1,'Artigas',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (2,'Canelones',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (3,'Cerro Largo',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (4,'Colonia',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (5,'Durazno',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (6,'Flores',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (7,'Florida',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (8,'Maldonado',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (9,'Paysand�',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (10,'R�o Negro',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (11,'Rivera',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (12,'Salto',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (13,'San Jos�',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (14,'Mercedes',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (15,'Tacuaremb�',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (16,'Lavalleja',4);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (17,'Montevideo',null);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (18,'Rocha',null);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (19,'Treinta y Tres',null);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (15,'Lavalleja',4);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (16,'Tacuaremb�',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (20,'Artigas',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (21,'Canelones',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (22,'Cerro Largo',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (23,'Colonia',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (24,'Durazno',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (25,'Flores',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (26,'Florida',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (27,'Maldonado',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (28,'Paysand�',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (29,'R�o Negro',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (30,'Rivera',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (31,'Salto',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (32,'San Jos�',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (33,'Mercedes',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (34,'Tacuaremb�',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (35,'Lavalleja',4);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (36,'Montevideo',null);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (37,'Rocha',null);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (38,'Treinta y Tres',null);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (39,'Lavalleja',4);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (40,'Tacuaremb�',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (41,'Artigas',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (42,'Canelones',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (43,'Cerro Largo',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (44,'Colonia',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (45,'Durazno',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (46,'Flores',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (47,'Florida',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (48,'Maldonado',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (49,'Paysand�',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (50,'R�o Negro',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (51,'Rivera',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (52,'Salto',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (53,'San Jos�',2);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (54,'Mercedes',1);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (55,'Tacuaremb�',3);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (56,'Lavalleja',4);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (57,'Montevideo',null);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (58,'Rocha',null);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (59,'Treinta y Tres',null);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (60,'Lavalleja',4);
Insert into C##PROYECTO.DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE,ID_ITR) values (61,'Tacuaremb�',3);
REM INSERTING into C##PROYECTO.ESTADOS
SET DEFINE OFF;
Insert into C##PROYECTO.ESTADOS (ID_ESTADO,NOMBRE,ACTIVO) values (1,'FINALIZADO',1);
Insert into C##PROYECTO.ESTADOS (ID_ESTADO,NOMBRE,ACTIVO) values (2,'CORRIENTE',1);
Insert into C##PROYECTO.ESTADOS (ID_ESTADO,NOMBRE,ACTIVO) values (3,'FUTURO',1);
REM INSERTING into C##PROYECTO.ESTUDIANTES
SET DEFINE OFF;
Insert into C##PROYECTO.ESTUDIANTES (ID_ESTUDIANTE,NOMBRE_USUARIO,GENERACION) values (34,'gonza.ruiz','2018');
REM INSERTING into C##PROYECTO.ESTUDIANTE_EVENTO
SET DEFINE OFF;
REM INSERTING into C##PROYECTO.EVENTOS
SET DEFINE OFF;
Insert into C##PROYECTO.EVENTOS (ID_EVENTO,FECHA_HORA_INICIO,FECHA_HORA_FINAL,TITULO,LOCALIZACION,TIPO_EVENTO,MODALIDAD,ID_ITR,ID_ESTADO,ID_MODALIDAD,ID_TIPO,ACTIVO) values (1,to_date('04-JUL-23','DD-MON-RR'),to_date('05-JUL-23','DD-MON-RR'),'pruebas','aaaaaaaaaaaaa','JORNADA_PRESENCIAL',null,1,2,2,null,1);
Insert into C##PROYECTO.EVENTOS (ID_EVENTO,FECHA_HORA_INICIO,FECHA_HORA_FINAL,TITULO,LOCALIZACION,TIPO_EVENTO,MODALIDAD,ID_ITR,ID_ESTADO,ID_MODALIDAD,ID_TIPO,ACTIVO) values (2,to_date('04-JUL-23','DD-MON-RR'),to_date('05-JUL-23','DD-MON-RR'),'pruebas2','aaaaaaaaaaaaa','JORNADA_PRESENCIAL',null,1,2,2,null,1);
Insert into C##PROYECTO.EVENTOS (ID_EVENTO,FECHA_HORA_INICIO,FECHA_HORA_FINAL,TITULO,LOCALIZACION,TIPO_EVENTO,MODALIDAD,ID_ITR,ID_ESTADO,ID_MODALIDAD,ID_TIPO,ACTIVO) values (3,to_date('04-JUL-23','DD-MON-RR'),to_date('05-JUL-23','DD-MON-RR'),'pruebas3','aaaaaaaaaaaaa','JORNADA_PRESENCIAL',null,1,2,2,null,0);
Insert into C##PROYECTO.EVENTOS (ID_EVENTO,FECHA_HORA_INICIO,FECHA_HORA_FINAL,TITULO,LOCALIZACION,TIPO_EVENTO,MODALIDAD,ID_ITR,ID_ESTADO,ID_MODALIDAD,ID_TIPO,ACTIVO) values (4,to_date('04-JUL-23','DD-MON-RR'),to_date('05-JUL-23','DD-MON-RR'),'pruebas4','aaaaaaaaaaaaa','JORNADA_PRESENCIAL',null,1,2,2,null,1);
REM INSERTING into C##PROYECTO.ITR
SET DEFINE OFF;
Insert into C##PROYECTO.ITR (ID_ITR,NOMBRE,ACTIVO) values (6,'Centro-Este',0);
Insert into C##PROYECTO.ITR (ID_ITR,NOMBRE,ACTIVO) values (1,'Suroeste',1);
Insert into C##PROYECTO.ITR (ID_ITR,NOMBRE,ACTIVO) values (2,'Centro-Sur',1);
Insert into C##PROYECTO.ITR (ID_ITR,NOMBRE,ACTIVO) values (3,'Norte',1);
Insert into C##PROYECTO.ITR (ID_ITR,NOMBRE,ACTIVO) values (4,'Este',1);
REM INSERTING into C##PROYECTO.JUSTIFICACIONES
SET DEFINE OFF;
REM INSERTING into C##PROYECTO.LOCALIDADES
SET DEFINE OFF;
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (1,'Canelones ciudad',2);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (2,'Santa Luc�a',2);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (3,'Las Piedras',2);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (4,'Pando',2);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (5,'Ciudad de la Costa',2);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (6,'Atl�ntida',2);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (7,'La Paz',2);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (8,'Sauce',2);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (9,'San Ram�n',2);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (10,'Toledo',2);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (11,'Artigas',1);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (12,'Bella Uni�n',1);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (13,'Tom�s Gomensoro',1);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (14,'Melo',3);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (15,'R�o Branco',3);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (16,'Fraile Muerto',3);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (17,'Colonia del Sacramento',4);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (18,'Nueva Helvecia',4);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (19,'Juan Lacaze',4);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (20,'Durazno',5);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (21,'Sarand� del Y�',5);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (22,'Blanquillo',5);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (23,'Trinidad',6);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (24,'Ismael Cortinas',6);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (25,'Juan Jos� Castro',6);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (26,'Florida',7);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (27,'Sarand� Grande',7);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (28,'Casupa',7);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (29,'Maldonado',8);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (30,'Punta del Este',8);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (31,'San Carlos',8);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (32,'Paysand�',9);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (33,'Guich�n',9);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (34,'Quebracho',9);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (35,'Fray Bentos',10);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (36,'Young',10);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (37,'Nuevo Berl�n',10);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (38,'Rivera',11);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (39,'Tranqueras',11);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (40,'Vichadero',11);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (41,'Salto',12);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (42,'Concordia',12);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (43,'Daym�n',12);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (44,'San Jos� de Mayo',13);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (45,'Ciudad del Plata',13);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (46,'Libertad',13);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (47,'Mercedes',14);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (48,'Dolores',14);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (49,'Bella Vista',14);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (50,'Tacuaremb�',15);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (51,'Paso de los Toros',15);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (52,'Ansina',15);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (53,'Minas',16);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (54,'Jos� Pedro Varela',16);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (55,'Sol�s de Mataojo',16);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (56,'Montevideo',17);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (57,'Pocitos',17);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (58,'Carrasco',17);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (59,'Rocha',18);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (60,'Chuy',18);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (61,'La Paloma',18);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (62,'Treinta y Tres',19);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (63,'Santa Clara de Olimar',19);
Insert into C##PROYECTO.LOCALIDADES (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values (64,'Vergara',19);
REM INSERTING into C##PROYECTO.MODALIDADES
SET DEFINE OFF;
Insert into C##PROYECTO.MODALIDADES (ID_MODALIDAD,NOMBRE,ACTIVO) values (1,'PRESENCIAL',1);
Insert into C##PROYECTO.MODALIDADES (ID_MODALIDAD,NOMBRE,ACTIVO) values (2,'SEMIPRESENCIAL',1);
Insert into C##PROYECTO.MODALIDADES (ID_MODALIDAD,NOMBRE,ACTIVO) values (3,'VIRTUAL',1);
REM INSERTING into C##PROYECTO.RECLAMOS
SET DEFINE OFF;
REM INSERTING into C##PROYECTO.STATUS_CERTIFICADOS
SET DEFINE OFF;
REM INSERTING into C##PROYECTO.STATUS_CONSTANCIA
SET DEFINE OFF;
REM INSERTING into C##PROYECTO.STATUS_JUSTIFICACION
SET DEFINE OFF;
REM INSERTING into C##PROYECTO.STATUS_RECLAMO
SET DEFINE OFF;
REM INSERTING into C##PROYECTO.TIPOSEVENTOS
SET DEFINE OFF;
REM INSERTING into C##PROYECTO.TUTORES
SET DEFINE OFF;
Insert into C##PROYECTO.TUTORES (ID_TUTOR,NOMBRE_USUARIO,TIPO,ID_AREA) values (16,'gon.ruiz','ENCARGADO',1);
REM INSERTING into C##PROYECTO.TUTOR_EVENTO
SET DEFINE OFF;
REM INSERTING into C##PROYECTO.USUARIOS
SET DEFINE OFF;
Insert into C##PROYECTO.USUARIOS (NOMBRE_USUARIO,NOMBRE1,NOMBRE2,APELLIDO1,APELLIDO2,FEC_NAC,GENERO,ID_DEPARTAMENTO,ID_LOCALIDAD,MAIL_INSTITUCIONAL,CONTRASENIA,TELEFONO,DOCUMENTO,ACTIVO,MAIL_PERSONAL,ID_ITR) values ('rodrigo.romano','Rodrigo','Ramiro','Romano','Rodriguez',to_date('15-JUL-99','DD-MON-RR'),'O',8,30,'rromano@tutores.utec.edu.uy','Rodrig0#','099123321','11111111',1,null,4);
Insert into C##PROYECTO.USUARIOS (NOMBRE_USUARIO,NOMBRE1,NOMBRE2,APELLIDO1,APELLIDO2,FEC_NAC,GENERO,ID_DEPARTAMENTO,ID_LOCALIDAD,MAIL_INSTITUCIONAL,CONTRASENIA,TELEFONO,DOCUMENTO,ACTIVO,MAIL_PERSONAL,ID_ITR) values ('p.perez','Pedro',null,'Perez','Postin',to_date('14-AUG-89','DD-MON-RR'),'M',15,51,'pperez@analistas.utec.edu.uy','Pedrop3#',null,'00000000',1,'pperez@gmail.com',1);
Insert into C##PROYECTO.USUARIOS (NOMBRE_USUARIO,NOMBRE1,NOMBRE2,APELLIDO1,APELLIDO2,FEC_NAC,GENERO,ID_DEPARTAMENTO,ID_LOCALIDAD,MAIL_INSTITUCIONAL,CONTRASENIA,TELEFONO,DOCUMENTO,ACTIVO,MAIL_PERSONAL,ID_ITR) values ('gluca','Gian','Luca','Battistin','Battistin',to_date('02-FEB-03','DD-MON-RR'),'M',18,61,'gluca@tutores.utec.edu.uy','Gianluc4#',null,'99999999',1,'gian.luca@gmail.com',2);
Insert into C##PROYECTO.USUARIOS (NOMBRE_USUARIO,NOMBRE1,NOMBRE2,APELLIDO1,APELLIDO2,FEC_NAC,GENERO,ID_DEPARTAMENTO,ID_LOCALIDAD,MAIL_INSTITUCIONAL,CONTRASENIA,TELEFONO,DOCUMENTO,ACTIVO,MAIL_PERSONAL,ID_ITR) values ('gonza.ruiz','Gonzalo','Lalo','Rushmore','Roshi',to_date('03-MAY-02','DD-MON-RR'),'M',19,64,'gonza.ruiz@estudiantes.utec.edu.uy','G0nzal0#','094475502','53689538',1,'gonza.ruiz@gmail.com',6);
Insert into C##PROYECTO.USUARIOS (NOMBRE_USUARIO,NOMBRE1,NOMBRE2,APELLIDO1,APELLIDO2,FEC_NAC,GENERO,ID_DEPARTAMENTO,ID_LOCALIDAD,MAIL_INSTITUCIONAL,CONTRASENIA,TELEFONO,DOCUMENTO,ACTIVO,MAIL_PERSONAL,ID_ITR) values ('gon.ruiz','Gonzalo',null,'Ruiz','Alvez',to_date('03-MAY-00','DD-MON-RR'),'M',12,42,'gon.ruiz@tutores.utec.edu.uy','Gonzal0#','094475502','53574721',1,'gonzalo.ruiz@gmail.com',3);
Insert into C##PROYECTO.USUARIOS (NOMBRE_USUARIO,NOMBRE1,NOMBRE2,APELLIDO1,APELLIDO2,FEC_NAC,GENERO,ID_DEPARTAMENTO,ID_LOCALIDAD,MAIL_INSTITUCIONAL,CONTRASENIA,TELEFONO,DOCUMENTO,ACTIVO,MAIL_PERSONAL,ID_ITR) values ('romi.caubarrere','Romina',null,'Caubarrere','Caubarrere',to_date('01-JUL-03','DD-MON-RR'),'F',6,23,'romi.caubarrere@estudiantes.utec.edu.uy','Caubarrer3#',null,'43662928',1,'romi.cauba@gmail.com',3);
--------------------------------------------------------
--  DDL for Index PK_ANALISTA_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_ANALISTA_ID" ON "C##PROYECTO"."ANALISTAS" ("ID_ANALISTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ANALI_EVENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_ANALI_EVENTO" ON "C##PROYECTO"."ANALISTA_EVENTO" ("ID_ANALISTA", "ID_EVENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_AREA_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_AREA_ID" ON "C##PROYECTO"."AREAS" ("ID_AREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CONST_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_CONST_ID" ON "C##PROYECTO"."CONSTANCIAS" ("ID_CONSTANCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ESTUD_EVENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_ESTUD_EVENTO" ON "C##PROYECTO"."ESTUDIANTE_EVENTO" ("ID_ESTUDIANTE", "ID_EVENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ESTUD_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_ESTUD_ID" ON "C##PROYECTO"."ESTUDIANTES" ("ID_ESTUDIANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EVENTO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_EVENTO_ID" ON "C##PROYECTO"."EVENTOS" ("ID_EVENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_ITR
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_ID_ITR" ON "C##PROYECTO"."ITR" ("ID_ITR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_LOCALI
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_ID_LOCALI" ON "C##PROYECTO"."LOCALIDADES" ("ID_LOCALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_JUSTIF_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_JUSTIF_ID" ON "C##PROYECTO"."JUSTIFICACIONES" ("ID_JUSTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MODALIDADES
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_MODALIDADES" ON "C##PROYECTO"."MODALIDADES" ("ID_MODALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RECL_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_RECL_ID" ON "C##PROYECTO"."RECLAMOS" ("ID_RECLAMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STATUS_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_STATUS_ID" ON "C##PROYECTO"."STATUS_CERTIFICADOS" ("ID_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STAT_CONST_IDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_STAT_CONST_IDS" ON "C##PROYECTO"."STATUS_CONSTANCIA" ("ID_STATUS", "ID_CONSTANCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STAT_JUST_IDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_STAT_JUST_IDS" ON "C##PROYECTO"."STATUS_JUSTIFICACION" ("ID_STATUS", "ID_JUSTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STAT_RECL_IDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_STAT_RECL_IDS" ON "C##PROYECTO"."STATUS_RECLAMO" ("ID_STATUS", "ID_RECLAMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TIPOSEVENTOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_TIPOSEVENTOS" ON "C##PROYECTO"."TIPOSEVENTOS" ("ID_TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TUTOR_EVENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_TUTOR_EVENTO" ON "C##PROYECTO"."TUTOR_EVENTO" ("ID_TUTOR", "ID_EVENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TUTOR_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_TUTOR_ID" ON "C##PROYECTO"."TUTORES" ("ID_TUTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USR_NOMBRE_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_USR_NOMBRE_USUARIO" ON "C##PROYECTO"."USUARIOS" ("NOMBRE_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010684
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."SYS_C0010684" ON "C##PROYECTO"."ESTADOS" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_AREA_NOMB
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."UK_AREA_NOMB" ON "C##PROYECTO"."AREAS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_ITR_NOMB
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."UK_ITR_NOMB" ON "C##PROYECTO"."ITR" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_LOCALI_NOMB
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."UK_LOCALI_NOMB" ON "C##PROYECTO"."LOCALIDADES" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USR_CORREO_PERSONAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."UK_USR_CORREO_PERSONAL" ON "C##PROYECTO"."USUARIOS" ("MAIL_PERSONAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USR_DOCUMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."UK_USR_DOCUMENTO" ON "C##PROYECTO"."USUARIOS" ("DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ANALISTA_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_ANALISTA_ID" ON "C##PROYECTO"."ANALISTAS" ("ID_ANALISTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ANALI_EVENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_ANALI_EVENTO" ON "C##PROYECTO"."ANALISTA_EVENTO" ("ID_ANALISTA", "ID_EVENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_AREA_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_AREA_ID" ON "C##PROYECTO"."AREAS" ("ID_AREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_AREA_NOMB
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."UK_AREA_NOMB" ON "C##PROYECTO"."AREAS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CONST_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_CONST_ID" ON "C##PROYECTO"."CONSTANCIAS" ("ID_CONSTANCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010684
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."SYS_C0010684" ON "C##PROYECTO"."ESTADOS" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ESTUD_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_ESTUD_ID" ON "C##PROYECTO"."ESTUDIANTES" ("ID_ESTUDIANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ESTUD_EVENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_ESTUD_EVENTO" ON "C##PROYECTO"."ESTUDIANTE_EVENTO" ("ID_ESTUDIANTE", "ID_EVENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EVENTO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_EVENTO_ID" ON "C##PROYECTO"."EVENTOS" ("ID_EVENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_ITR
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_ID_ITR" ON "C##PROYECTO"."ITR" ("ID_ITR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_ITR_NOMB
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."UK_ITR_NOMB" ON "C##PROYECTO"."ITR" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_JUSTIF_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_JUSTIF_ID" ON "C##PROYECTO"."JUSTIFICACIONES" ("ID_JUSTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_LOCALI
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_ID_LOCALI" ON "C##PROYECTO"."LOCALIDADES" ("ID_LOCALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_LOCALI_NOMB
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."UK_LOCALI_NOMB" ON "C##PROYECTO"."LOCALIDADES" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MODALIDADES
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_MODALIDADES" ON "C##PROYECTO"."MODALIDADES" ("ID_MODALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RECL_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_RECL_ID" ON "C##PROYECTO"."RECLAMOS" ("ID_RECLAMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STATUS_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_STATUS_ID" ON "C##PROYECTO"."STATUS_CERTIFICADOS" ("ID_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STAT_CONST_IDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_STAT_CONST_IDS" ON "C##PROYECTO"."STATUS_CONSTANCIA" ("ID_STATUS", "ID_CONSTANCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STAT_JUST_IDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_STAT_JUST_IDS" ON "C##PROYECTO"."STATUS_JUSTIFICACION" ("ID_STATUS", "ID_JUSTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STAT_RECL_IDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_STAT_RECL_IDS" ON "C##PROYECTO"."STATUS_RECLAMO" ("ID_STATUS", "ID_RECLAMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TIPOSEVENTOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_TIPOSEVENTOS" ON "C##PROYECTO"."TIPOSEVENTOS" ("ID_TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TUTOR_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_TUTOR_ID" ON "C##PROYECTO"."TUTORES" ("ID_TUTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TUTOR_EVENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_TUTOR_EVENTO" ON "C##PROYECTO"."TUTOR_EVENTO" ("ID_TUTOR", "ID_EVENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USR_NOMBRE_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."PK_USR_NOMBRE_USUARIO" ON "C##PROYECTO"."USUARIOS" ("NOMBRE_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USR_CORREO_PERSONAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."UK_USR_CORREO_PERSONAL" ON "C##PROYECTO"."USUARIOS" ("MAIL_PERSONAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USR_DOCUMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PROYECTO"."UK_USR_DOCUMENTO" ON "C##PROYECTO"."USUARIOS" ("DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger SET_ANALI_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_ANALI_ID_TRIGGER" 
BEFORE INSERT ON ANALISTAS
FOR EACH ROW
BEGIN
  :NEW.id_analista := analistas_id_seq.NEXTVAL;
END;
/
ALTER TRIGGER "C##PROYECTO"."SET_ANALI_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_AREAS_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_AREAS_ID_TRIGGER" 
BEFORE INSERT ON AREAS
FOR EACH ROW
BEGIN
  :NEW.id_area := areas_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_AREAS_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_CONST_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_CONST_ID_TRIGGER" 
BEFORE INSERT ON CONSTANCIAS
FOR EACH ROW
BEGIN
  :NEW.id_constancia := constancias_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_CONST_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_DEPA_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_DEPA_ID_TRIGGER" 
BEFORE INSERT ON DEPARTAMENTOS
FOR EACH ROW
BEGIN
  :NEW.id_departamento := depa_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_DEPA_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_ESTADO_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_ESTADO_ID_TRIGGER" 
BEFORE INSERT ON ESTADOS
FOR EACH ROW
BEGIN
  :NEW.ID_ESTADO:= SEQ_ESTADOS.NEXTVAL;
END;

/
ALTER TRIGGER "C##PROYECTO"."SET_ESTADO_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_ESTUD_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_ESTUD_ID_TRIGGER" 
BEFORE INSERT ON ESTUDIANTES
FOR EACH ROW
BEGIN
  :NEW.id_estudiante := estud_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_ESTUD_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_EVENTOS_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_EVENTOS_ID_TRIGGER" 
BEFORE INSERT ON EVENTOS
FOR EACH ROW
BEGIN
  :NEW.id_evento := event_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_EVENTOS_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_ITR_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_ITR_ID_TRIGGER" 
BEFORE INSERT ON ITR
FOR EACH ROW
BEGIN
  :NEW.id_itr := itr_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_ITR_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_JUSTI_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_JUSTI_ID_TRIGGER" 
BEFORE INSERT ON JUSTIFICACIONES
FOR EACH ROW
BEGIN
  :NEW.id_justificacion := justi_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_JUSTI_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_LOCALI_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_LOCALI_ID_TRIGGER" 
BEFORE INSERT ON LOCALIDADES
FOR EACH ROW
BEGIN
  :NEW.id_localidad := locali_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_LOCALI_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_MODALIDAD_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_MODALIDAD_ID_TRIGGER" 
BEFORE INSERT ON MODALIDADES
FOR EACH ROW
BEGIN
  :NEW.ID_MODALIDAD := SEQ_MODALIDADES.NEXTVAL;
END;

/
ALTER TRIGGER "C##PROYECTO"."SET_MODALIDAD_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_RECL_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_RECL_ID_TRIGGER" 
BEFORE INSERT ON RECLAMOS
FOR EACH ROW
BEGIN
  :NEW.id_reclamo := recl_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_RECL_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_STAT_CERT_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_STAT_CERT_ID_TRIGGER" 
BEFORE INSERT ON STATUS_CERTIFICADOS
FOR EACH ROW
BEGIN
  :NEW.id_status := stat_cert_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_STAT_CERT_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_TUTORES_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_TUTORES_ID_TRIGGER" 
BEFORE INSERT ON TUTORES
FOR EACH ROW
BEGIN
  :NEW.id_tutor := tutores_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_TUTORES_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_USR_ACTIVO_DEFAULT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_USR_ACTIVO_DEFAULT" 
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN
  :NEW.activo := 0; -- Settea el valor de la columna 'activo' (1 para activo, 0 para inactivo)
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_USR_ACTIVO_DEFAULT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_INSERT_EVENTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."T_INSERT_EVENTO" 
BEFORE INSERT ON EVENTOS
FOR EACH ROW
BEGIN
    SELECT SEQ_ID_EVENTO.NEXTVAL INTO :NEW.ID_EVENTO FROM DUAL;
END;

/
ALTER TRIGGER "C##PROYECTO"."T_INSERT_EVENTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_ANALI_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_ANALI_ID_TRIGGER" 
BEFORE INSERT ON ANALISTAS
FOR EACH ROW
BEGIN
  :NEW.id_analista := analistas_id_seq.NEXTVAL;
END;
/
ALTER TRIGGER "C##PROYECTO"."SET_ANALI_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_AREAS_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_AREAS_ID_TRIGGER" 
BEFORE INSERT ON AREAS
FOR EACH ROW
BEGIN
  :NEW.id_area := areas_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_AREAS_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_CONST_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_CONST_ID_TRIGGER" 
BEFORE INSERT ON CONSTANCIAS
FOR EACH ROW
BEGIN
  :NEW.id_constancia := constancias_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_CONST_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_DEPA_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_DEPA_ID_TRIGGER" 
BEFORE INSERT ON DEPARTAMENTOS
FOR EACH ROW
BEGIN
  :NEW.id_departamento := depa_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_DEPA_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_ESTADO_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_ESTADO_ID_TRIGGER" 
BEFORE INSERT ON ESTADOS
FOR EACH ROW
BEGIN
  :NEW.ID_ESTADO:= SEQ_ESTADOS.NEXTVAL;
END;

/
ALTER TRIGGER "C##PROYECTO"."SET_ESTADO_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_ESTUD_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_ESTUD_ID_TRIGGER" 
BEFORE INSERT ON ESTUDIANTES
FOR EACH ROW
BEGIN
  :NEW.id_estudiante := estud_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_ESTUD_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_EVENTOS_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_EVENTOS_ID_TRIGGER" 
BEFORE INSERT ON EVENTOS
FOR EACH ROW
BEGIN
  :NEW.id_evento := event_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_EVENTOS_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_INSERT_EVENTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."T_INSERT_EVENTO" 
BEFORE INSERT ON EVENTOS
FOR EACH ROW
BEGIN
    SELECT SEQ_ID_EVENTO.NEXTVAL INTO :NEW.ID_EVENTO FROM DUAL;
END;

/
ALTER TRIGGER "C##PROYECTO"."T_INSERT_EVENTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_ITR_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_ITR_ID_TRIGGER" 
BEFORE INSERT ON ITR
FOR EACH ROW
BEGIN
  :NEW.id_itr := itr_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_ITR_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_JUSTI_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_JUSTI_ID_TRIGGER" 
BEFORE INSERT ON JUSTIFICACIONES
FOR EACH ROW
BEGIN
  :NEW.id_justificacion := justi_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_JUSTI_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_LOCALI_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_LOCALI_ID_TRIGGER" 
BEFORE INSERT ON LOCALIDADES
FOR EACH ROW
BEGIN
  :NEW.id_localidad := locali_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_LOCALI_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_MODALIDAD_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_MODALIDAD_ID_TRIGGER" 
BEFORE INSERT ON MODALIDADES
FOR EACH ROW
BEGIN
  :NEW.ID_MODALIDAD := SEQ_MODALIDADES.NEXTVAL;
END;

/
ALTER TRIGGER "C##PROYECTO"."SET_MODALIDAD_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_RECL_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_RECL_ID_TRIGGER" 
BEFORE INSERT ON RECLAMOS
FOR EACH ROW
BEGIN
  :NEW.id_reclamo := recl_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_RECL_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_STAT_CERT_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_STAT_CERT_ID_TRIGGER" 
BEFORE INSERT ON STATUS_CERTIFICADOS
FOR EACH ROW
BEGIN
  :NEW.id_status := stat_cert_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_STAT_CERT_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_TUTORES_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_TUTORES_ID_TRIGGER" 
BEFORE INSERT ON TUTORES
FOR EACH ROW
BEGIN
  :NEW.id_tutor := tutores_id_seq.NEXTVAL;
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_TUTORES_ID_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_USR_ACTIVO_DEFAULT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PROYECTO"."SET_USR_ACTIVO_DEFAULT" 
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN
  :NEW.activo := 0; -- Settea el valor de la columna 'activo' (1 para activo, 0 para inactivo)
END;


/
ALTER TRIGGER "C##PROYECTO"."SET_USR_ACTIVO_DEFAULT" ENABLE;
--------------------------------------------------------
--  Constraints for Table ANALISTAS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."ANALISTAS" MODIFY ("ID_ANALISTA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ANALISTAS" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ANALISTAS" ADD CONSTRAINT "PK_ANALISTA_ID" PRIMARY KEY ("ID_ANALISTA")
  USING INDEX "C##PROYECTO"."PK_ANALISTA_ID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ANALISTA_EVENTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."ANALISTA_EVENTO" MODIFY ("ID_ANALISTA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ANALISTA_EVENTO" MODIFY ("ID_EVENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ANALISTA_EVENTO" ADD CONSTRAINT "PK_ANALI_EVENTO" PRIMARY KEY ("ID_ANALISTA", "ID_EVENTO")
  USING INDEX "C##PROYECTO"."PK_ANALI_EVENTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AREAS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."AREAS" MODIFY ("ID_AREA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."AREAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."AREAS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."AREAS" ADD CONSTRAINT "PK_AREA_ID" PRIMARY KEY ("ID_AREA")
  USING INDEX "C##PROYECTO"."PK_AREA_ID"  ENABLE;
  ALTER TABLE "C##PROYECTO"."AREAS" ADD CONSTRAINT "UK_AREA_NOMB" UNIQUE ("NOMBRE")
  USING INDEX "C##PROYECTO"."UK_AREA_NOMB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONSTANCIAS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."CONSTANCIAS" MODIFY ("ID_CONSTANCIA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."CONSTANCIAS" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."CONSTANCIAS" MODIFY ("ID_EVENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."CONSTANCIAS" MODIFY ("DETALLE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."CONSTANCIAS" MODIFY ("FECHA_HORA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."CONSTANCIAS" ADD CONSTRAINT "PK_CONST_ID" PRIMARY KEY ("ID_CONSTANCIA")
  USING INDEX "C##PROYECTO"."PK_CONST_ID"  ENABLE;
  ALTER TABLE "C##PROYECTO"."CONSTANCIAS" MODIFY ("TIPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTOS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."DEPARTAMENTOS" MODIFY ("ID_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."DEPARTAMENTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADOS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."ESTADOS" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ESTADOS" ADD PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##PROYECTO"."ESTADOS" MODIFY ("ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ESTADOS" ADD CONSTRAINT "CK_ACTIVO_ESTADOS" CHECK (ACTIVO IN (1, 0)) ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."ESTUDIANTES" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ESTUDIANTES" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ESTUDIANTES" MODIFY ("GENERACION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ESTUDIANTES" ADD CONSTRAINT "PK_ESTUD_ID" PRIMARY KEY ("ID_ESTUDIANTE")
  USING INDEX "C##PROYECTO"."PK_ESTUD_ID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTUDIANTE_EVENTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."ESTUDIANTE_EVENTO" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ESTUDIANTE_EVENTO" MODIFY ("ID_EVENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ESTUDIANTE_EVENTO" MODIFY ("CALIFICACION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ESTUDIANTE_EVENTO" MODIFY ("ASISTENCIA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ESTUDIANTE_EVENTO" ADD CONSTRAINT "CHK_ESTUD_EVEN_ASIST" CHECK (calificacion IN ('S', 'N', 'P')) ENABLE;
  ALTER TABLE "C##PROYECTO"."ESTUDIANTE_EVENTO" ADD CONSTRAINT "PK_ESTUD_EVENTO" PRIMARY KEY ("ID_ESTUDIANTE", "ID_EVENTO")
  USING INDEX "C##PROYECTO"."PK_ESTUD_EVENTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENTOS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."EVENTOS" MODIFY ("ID_EVENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."EVENTOS" MODIFY ("FECHA_HORA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."EVENTOS" MODIFY ("FECHA_HORA_FINAL" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."EVENTOS" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."EVENTOS" ADD CONSTRAINT "PK_EVENTO_ID" PRIMARY KEY ("ID_EVENTO")
  USING INDEX "C##PROYECTO"."PK_EVENTO_ID"  ENABLE;
  ALTER TABLE "C##PROYECTO"."EVENTOS" MODIFY ("LOCALIZACION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."EVENTOS" MODIFY ("ID_ITR" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."EVENTOS" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."EVENTOS" MODIFY ("ACTIVO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITR
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."ITR" ADD CONSTRAINT "CHK_ITR_ACTIVO" CHECK ( activo IN (1, 0)) ENABLE;
  ALTER TABLE "C##PROYECTO"."ITR" MODIFY ("ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ITR" MODIFY ("ID_ITR" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ITR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."ITR" ADD CONSTRAINT "PK_ID_ITR" PRIMARY KEY ("ID_ITR")
  USING INDEX "C##PROYECTO"."PK_ID_ITR"  ENABLE;
  ALTER TABLE "C##PROYECTO"."ITR" ADD CONSTRAINT "UK_ITR_NOMB" UNIQUE ("NOMBRE")
  USING INDEX "C##PROYECTO"."UK_ITR_NOMB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JUSTIFICACIONES
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."JUSTIFICACIONES" MODIFY ("ID_JUSTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."JUSTIFICACIONES" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."JUSTIFICACIONES" MODIFY ("ID_EVENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."JUSTIFICACIONES" MODIFY ("DETALLE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."JUSTIFICACIONES" MODIFY ("FECHA_HORA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."JUSTIFICACIONES" ADD CONSTRAINT "PK_JUSTIF_ID" PRIMARY KEY ("ID_JUSTIFICACION")
  USING INDEX "C##PROYECTO"."PK_JUSTIF_ID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCALIDADES
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."LOCALIDADES" MODIFY ("ID_LOCALIDAD" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."LOCALIDADES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."LOCALIDADES" MODIFY ("ID_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."LOCALIDADES" ADD CONSTRAINT "PK_ID_LOCALI" PRIMARY KEY ("ID_LOCALIDAD")
  USING INDEX "C##PROYECTO"."PK_ID_LOCALI"  ENABLE;
  ALTER TABLE "C##PROYECTO"."LOCALIDADES" ADD CONSTRAINT "UK_LOCALI_NOMB" UNIQUE ("NOMBRE")
  USING INDEX "C##PROYECTO"."UK_LOCALI_NOMB"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MODALIDADES
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."MODALIDADES" MODIFY ("ID_MODALIDAD" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."MODALIDADES" ADD CONSTRAINT "PK_MODALIDADES" PRIMARY KEY ("ID_MODALIDAD")
  USING INDEX "C##PROYECTO"."PK_MODALIDADES"  ENABLE;
  ALTER TABLE "C##PROYECTO"."MODALIDADES" MODIFY ("ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."MODALIDADES" ADD CONSTRAINT "CK_ACTIVO_MODALIDADES" CHECK (ACTIVO IN (1, 0)) ENABLE;
--------------------------------------------------------
--  Constraints for Table RECLAMOS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."RECLAMOS" MODIFY ("ID_RECLAMO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."RECLAMOS" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."RECLAMOS" MODIFY ("ID_EVENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."RECLAMOS" MODIFY ("DETALLE" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."RECLAMOS" MODIFY ("FECHA_HORA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."RECLAMOS" ADD CONSTRAINT "PK_RECL_ID" PRIMARY KEY ("ID_RECLAMO")
  USING INDEX "C##PROYECTO"."PK_RECL_ID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUS_CERTIFICADOS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."STATUS_CERTIFICADOS" MODIFY ("ID_STATUS" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."STATUS_CERTIFICADOS" MODIFY ("NOMBRE_ACCION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."STATUS_CERTIFICADOS" ADD CONSTRAINT "PK_STATUS_ID" PRIMARY KEY ("ID_STATUS")
  USING INDEX "C##PROYECTO"."PK_STATUS_ID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUS_CONSTANCIA
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."STATUS_CONSTANCIA" MODIFY ("ID_STATUS" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."STATUS_CONSTANCIA" MODIFY ("ID_CONSTANCIA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."STATUS_CONSTANCIA" ADD CONSTRAINT "PK_STAT_CONST_IDS" PRIMARY KEY ("ID_STATUS", "ID_CONSTANCIA")
  USING INDEX "C##PROYECTO"."PK_STAT_CONST_IDS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUS_JUSTIFICACION
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."STATUS_JUSTIFICACION" MODIFY ("ID_STATUS" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."STATUS_JUSTIFICACION" MODIFY ("ID_JUSTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."STATUS_JUSTIFICACION" ADD CONSTRAINT "PK_STAT_JUST_IDS" PRIMARY KEY ("ID_STATUS", "ID_JUSTIFICACION")
  USING INDEX "C##PROYECTO"."PK_STAT_JUST_IDS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUS_RECLAMO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."STATUS_RECLAMO" MODIFY ("ID_STATUS" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."STATUS_RECLAMO" MODIFY ("ID_RECLAMO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."STATUS_RECLAMO" ADD CONSTRAINT "PK_STAT_RECL_IDS" PRIMARY KEY ("ID_STATUS", "ID_RECLAMO")
  USING INDEX "C##PROYECTO"."PK_STAT_RECL_IDS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPOSEVENTOS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."TIPOSEVENTOS" MODIFY ("ID_TIPO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."TIPOSEVENTOS" ADD CONSTRAINT "PK_TIPOSEVENTOS" PRIMARY KEY ("ID_TIPO")
  USING INDEX "C##PROYECTO"."PK_TIPOSEVENTOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TUTORES
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."TUTORES" MODIFY ("ID_TUTOR" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."TUTORES" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."TUTORES" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."TUTORES" MODIFY ("ID_AREA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."TUTORES" ADD CONSTRAINT "PK_TUTOR_ID" PRIMARY KEY ("ID_TUTOR")
  USING INDEX "C##PROYECTO"."PK_TUTOR_ID"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TUTOR_EVENTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."TUTOR_EVENTO" MODIFY ("ID_TUTOR" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."TUTOR_EVENTO" MODIFY ("ID_EVENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."TUTOR_EVENTO" ADD CONSTRAINT "PK_TUTOR_EVENTO" PRIMARY KEY ("ID_TUTOR", "ID_EVENTO")
  USING INDEX "C##PROYECTO"."PK_TUTOR_EVENTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("NOMBRE1" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("APELLIDO1" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("APELLIDO2" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("FEC_NAC" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("GENERO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("ID_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("ID_LOCALIDAD" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("ID_ITR" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("MAIL_INSTITUCIONAL" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("CONTRASENIA" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" MODIFY ("ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "C##PROYECTO"."USUARIOS" ADD CONSTRAINT "CHK_USR_GENERO" CHECK ( genero IN ('F', 'M', 'O') ) ENABLE;
  ALTER TABLE "C##PROYECTO"."USUARIOS" ADD CONSTRAINT "CHK_USR_ACTIVO" CHECK ( activo IN (1, 0)          ) ENABLE;
  ALTER TABLE "C##PROYECTO"."USUARIOS" ADD CONSTRAINT "PK_USR_NOMBRE_USUARIO" PRIMARY KEY ("NOMBRE_USUARIO")
  USING INDEX "C##PROYECTO"."PK_USR_NOMBRE_USUARIO"  ENABLE;
  ALTER TABLE "C##PROYECTO"."USUARIOS" ADD CONSTRAINT "UK_USR_DOCUMENTO" UNIQUE ("DOCUMENTO")
  USING INDEX "C##PROYECTO"."UK_USR_DOCUMENTO"  ENABLE;
  ALTER TABLE "C##PROYECTO"."USUARIOS" ADD CONSTRAINT "UK_USR_CORREO_PERSONAL" UNIQUE ("MAIL_PERSONAL")
  USING INDEX "C##PROYECTO"."UK_USR_CORREO_PERSONAL"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANALISTAS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."ANALISTAS" ADD CONSTRAINT "FK_ANALI_NOMB_USER" FOREIGN KEY ("NOMBRE_USUARIO")
	  REFERENCES "C##PROYECTO"."USUARIOS" ("NOMBRE_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANALISTA_EVENTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."ANALISTA_EVENTO" ADD CONSTRAINT "FK_ANALI_EVEN_ANALISTA" FOREIGN KEY ("ID_ANALISTA")
	  REFERENCES "C##PROYECTO"."ANALISTAS" ("ID_ANALISTA") ENABLE;
  ALTER TABLE "C##PROYECTO"."ANALISTA_EVENTO" ADD CONSTRAINT "FK_ANALI_EVEN_EVENTO" FOREIGN KEY ("ID_EVENTO")
	  REFERENCES "C##PROYECTO"."EVENTOS" ("ID_EVENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONSTANCIAS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."CONSTANCIAS" ADD CONSTRAINT "FK_CONST_ID_ESTUD" FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "C##PROYECTO"."ESTUDIANTES" ("ID_ESTUDIANTE") ENABLE;
  ALTER TABLE "C##PROYECTO"."CONSTANCIAS" ADD CONSTRAINT "FK_CONST_ID_EVENTO" FOREIGN KEY ("ID_EVENTO")
	  REFERENCES "C##PROYECTO"."EVENTOS" ("ID_EVENTO") ENABLE;
  ALTER TABLE "C##PROYECTO"."CONSTANCIAS" ADD CONSTRAINT "FK_CONST_ID_ANALI" FOREIGN KEY ("ID_ANALISTA")
	  REFERENCES "C##PROYECTO"."ANALISTAS" ("ID_ANALISTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTAMENTOS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."DEPARTAMENTOS" ADD CONSTRAINT "FK_DEPA_ID_ITR" FOREIGN KEY ("ID_ITR")
	  REFERENCES "C##PROYECTO"."ITR" ("ID_ITR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."ESTUDIANTES" ADD CONSTRAINT "FK_ESTUD_NOMB_USR" FOREIGN KEY ("NOMBRE_USUARIO")
	  REFERENCES "C##PROYECTO"."USUARIOS" ("NOMBRE_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTE_EVENTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."ESTUDIANTE_EVENTO" ADD CONSTRAINT "FK_ESTUD_EVEN_ANALISTA" FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "C##PROYECTO"."ESTUDIANTES" ("ID_ESTUDIANTE") ENABLE;
  ALTER TABLE "C##PROYECTO"."ESTUDIANTE_EVENTO" ADD CONSTRAINT "FK_ESTUD_EVEN_EVENTO" FOREIGN KEY ("ID_EVENTO")
	  REFERENCES "C##PROYECTO"."EVENTOS" ("ID_EVENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENTOS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."EVENTOS" ADD CONSTRAINT "FK_EVENTO_ID_ITR" FOREIGN KEY ("ID_ITR")
	  REFERENCES "C##PROYECTO"."ITR" ("ID_ITR") ENABLE;
  ALTER TABLE "C##PROYECTO"."EVENTOS" ADD CONSTRAINT "FK_EVENTO_ID_MODALIDAD" FOREIGN KEY ("ID_MODALIDAD")
	  REFERENCES "C##PROYECTO"."MODALIDADES" ("ID_MODALIDAD") ENABLE;
  ALTER TABLE "C##PROYECTO"."EVENTOS" ADD CONSTRAINT "FK_EVENTO_ID_TIPO" FOREIGN KEY ("ID_TIPO")
	  REFERENCES "C##PROYECTO"."TIPOSEVENTOS" ("ID_TIPO") ENABLE;
  ALTER TABLE "C##PROYECTO"."EVENTOS" ADD CONSTRAINT "FK_EVENTO_ESTADO" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "C##PROYECTO"."ESTADOS" ("ID_ESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUSTIFICACIONES
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."JUSTIFICACIONES" ADD CONSTRAINT "FK_JUSTIF_ID_ESTUD" FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "C##PROYECTO"."ESTUDIANTES" ("ID_ESTUDIANTE") ENABLE;
  ALTER TABLE "C##PROYECTO"."JUSTIFICACIONES" ADD CONSTRAINT "FK_JUSTIF_ID_EVENTO" FOREIGN KEY ("ID_EVENTO")
	  REFERENCES "C##PROYECTO"."EVENTOS" ("ID_EVENTO") ENABLE;
  ALTER TABLE "C##PROYECTO"."JUSTIFICACIONES" ADD CONSTRAINT "FK_JUSTIF_ID_ANALI" FOREIGN KEY ("ID_ANALISTA")
	  REFERENCES "C##PROYECTO"."ANALISTAS" ("ID_ANALISTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECLAMOS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."RECLAMOS" ADD CONSTRAINT "FK_RECL_ID_ESTUD" FOREIGN KEY ("ID_ESTUDIANTE")
	  REFERENCES "C##PROYECTO"."ESTUDIANTES" ("ID_ESTUDIANTE") ENABLE;
  ALTER TABLE "C##PROYECTO"."RECLAMOS" ADD CONSTRAINT "FK_RECL_ID_EVENTO" FOREIGN KEY ("ID_EVENTO")
	  REFERENCES "C##PROYECTO"."EVENTOS" ("ID_EVENTO") ENABLE;
  ALTER TABLE "C##PROYECTO"."RECLAMOS" ADD CONSTRAINT "FK_RECL_ID_ANALI" FOREIGN KEY ("ID_ANALISTA")
	  REFERENCES "C##PROYECTO"."ANALISTAS" ("ID_ANALISTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATUS_CONSTANCIA
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."STATUS_CONSTANCIA" ADD CONSTRAINT "FK_STAT_CONST_STATUS" FOREIGN KEY ("ID_STATUS")
	  REFERENCES "C##PROYECTO"."STATUS_CERTIFICADOS" ("ID_STATUS") ENABLE;
  ALTER TABLE "C##PROYECTO"."STATUS_CONSTANCIA" ADD CONSTRAINT "FK_STAT_CONST_CONSTANCIA" FOREIGN KEY ("ID_CONSTANCIA")
	  REFERENCES "C##PROYECTO"."CONSTANCIAS" ("ID_CONSTANCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATUS_JUSTIFICACION
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."STATUS_JUSTIFICACION" ADD CONSTRAINT "FK_STAT_JUST_STATUS" FOREIGN KEY ("ID_STATUS")
	  REFERENCES "C##PROYECTO"."STATUS_CERTIFICADOS" ("ID_STATUS") ENABLE;
  ALTER TABLE "C##PROYECTO"."STATUS_JUSTIFICACION" ADD CONSTRAINT "FK_STAT_JUST_JUSTIFICACION" FOREIGN KEY ("ID_JUSTIFICACION")
	  REFERENCES "C##PROYECTO"."JUSTIFICACIONES" ("ID_JUSTIFICACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATUS_RECLAMO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."STATUS_RECLAMO" ADD CONSTRAINT "FK_STAT_RECL_STATUS" FOREIGN KEY ("ID_STATUS")
	  REFERENCES "C##PROYECTO"."STATUS_CERTIFICADOS" ("ID_STATUS") ENABLE;
  ALTER TABLE "C##PROYECTO"."STATUS_RECLAMO" ADD CONSTRAINT "FK_STAT_RECL_RECLAMO" FOREIGN KEY ("ID_RECLAMO")
	  REFERENCES "C##PROYECTO"."RECLAMOS" ("ID_RECLAMO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TUTORES
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."TUTORES" ADD CONSTRAINT "FK_TUTOR_NOMB_USER" FOREIGN KEY ("NOMBRE_USUARIO")
	  REFERENCES "C##PROYECTO"."USUARIOS" ("NOMBRE_USUARIO") ENABLE;
  ALTER TABLE "C##PROYECTO"."TUTORES" ADD CONSTRAINT "FK_TUTOR_ID_AREA" FOREIGN KEY ("ID_AREA")
	  REFERENCES "C##PROYECTO"."AREAS" ("ID_AREA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TUTOR_EVENTO
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."TUTOR_EVENTO" ADD CONSTRAINT "FK_TUTO_EVEN_TUTOR" FOREIGN KEY ("ID_TUTOR")
	  REFERENCES "C##PROYECTO"."TUTORES" ("ID_TUTOR") ENABLE;
  ALTER TABLE "C##PROYECTO"."TUTOR_EVENTO" ADD CONSTRAINT "FK_TUTO_EVEN_EVENTO" FOREIGN KEY ("ID_EVENTO")
	  REFERENCES "C##PROYECTO"."EVENTOS" ("ID_EVENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "C##PROYECTO"."USUARIOS" ADD CONSTRAINT "FK_USR_ID_ITR" FOREIGN KEY ("ID_ITR")
	  REFERENCES "C##PROYECTO"."ITR" ("ID_ITR") ENABLE;
  ALTER TABLE "C##PROYECTO"."USUARIOS" ADD CONSTRAINT "FK_USR_ID_LOCALI" FOREIGN KEY ("ID_LOCALIDAD")
	  REFERENCES "C##PROYECTO"."LOCALIDADES" ("ID_LOCALIDAD") ENABLE;
